import Link from "next/link";
import { Photo } from "@/components/shared";
import { HomeSlider, FeaturedProducts, References } from "@/components/woodmart-home";
import { categories, collections, site } from "@/lib/data";
import { FactoryGallery } from "@/components/factory-gallery";
import { whatsappUrl } from "@/lib/contact";
import { getProducts } from "@/lib/db";
export const dynamic = "force-dynamic";
export const metadata = { ...(site.domain ? { alternates: { canonical: site.domain.replace(/\/$/, "") } } : {}) };
export default async function Home() {
  const products = await getProducts();
  return <>
    <section className="wd-hero-area"><div className="wrap wd-hero-layout"><aside className="wd-sidebar" aria-label="Ürün kategorileri">
      {categories.map((c, i) => <Link key={c.slug} href={`/urunler?kategori=${c.slug}`}><span className="wd-category-icon" aria-hidden="true">{["▱", "▤", "▥", "▰", "▧", "◇", "☆"][i]}</span>{c.name}<span className="wd-chevron">&gt;</span></Link>)}
      {[ ["/koleksiyonlar", "◇", "Koleksiyonlar"], ["/ozel-uretim", "✂", "Özel Üretim"], ["/kumas-renk-kartelasi", "▧", "Kumaş & Renk Kartelası"], ["/urunler?yeni=1", "✧", "Yeni Ürünler"], ["/urunler?kampanya=1", "%", "Kampanyalar"] ].map(([href, icon, label]) => <Link href={href} key={href}><span className="wd-category-icon">{icon}</span>{label}<span className="wd-chevron">&gt;</span></Link>)}
    </aside><HomeSlider/></div></section>
    <section className="wrap wd-section" id="kategoriler"><div className="wd-section-heading"><p>Zenn Bedding KOLEKSİYONLARI</p><h2>ÖNE ÇIKAN KATEGORİLER</h2><p>Yaşam alanınız için tasarlanan konforlu ve zamansız seçenekler.</p></div><div className="wd-category-list wd-category-list-vertical">{categories.map(c => <Link href={`/urunler?kategori=${c.slug}`} key={c.slug}>{c.name}<span aria-hidden="true">&gt;</span></Link>)}</div></section>
    <section className="wrap wd-section wd-featured"><div className="wd-section-heading"><p>Zenn Bedding UYKU & YAŞAM</p><h2>ÖNE ÇIKAN ÜRÜNLER</h2><p>Yatak odanıza yeni bir dokunuş katacak modellerimizi keşfedin.</p></div><FeaturedProducts products={products}/></section>
    <section className="wd-spotlight"><div className="wrap"><div className="wd-spotlight-image"><Photo src="/images/modern.webp" alt="Modern Konfor yatak odası koleksiyonu"/></div><div className="wd-spotlight-copy"><p>KOLEKSİYONU YAKINDAN TANIYIN</p><h2>Modern Konfor –<br/>Zamansız Tasarım.</h2><div className="wd-specs"><div><b>TASARIM</b><span>Zenn Bedding</span></div><div><b>DOKULAR</b><span>Keten, bukle, kadife</span></div><div><b>SEÇENEKLER</b><span>Size özel ölçüler</span></div></div><Link href="/koleksiyonlar/modern-koleksiyon" className="button outline">KOLEKSİYONU İNCELE</Link></div></div></section>
    <section className="wrap wd-about"><div><p>YAŞAM ALANINIZ İÇİN HER DETAY</p><h2>Zenn Bedding – Uyku & Yaşam</h2><p>Konfor, özenli işçilik ve zamansız tasarımı bir araya getiriyoruz. Baza, başlık ve yataklarımızı kendi tesisimizde üretiyor; ölçü, kumaş ve renk seçeneklerini sizinle birlikte belirliyoruz.</p><div className="wd-about-actions"><Link href="/biz-kimiz" className="button">BİZ KİMİZ</Link><Link href="/iletisim" className="button outline">İLETİŞİME GEÇİN</Link></div></div><Photo src="/images/headboard.webp" alt="Zenn Bedding döşemeli başlık detayları"/></section>
    <section className="wd-contact-banner"><p>ÖLÇÜ, RENK VE KUMAŞ SEÇENEKLERİ</p><h2>SİZE ÖZEL BİR TASARIM</h2><p>Hayalinizdeki yatak odasını birlikte şekillendirelim.</p><div className="actions"><Link href="/ozel-uretim" className="button">ÖZEL ÜRETİMİ KEŞFEDİN</Link><Link href="/kumas-renk-kartelasi" className="button outline">KUMAŞ & RENK KARTELASI</Link></div></section>
    <section className="wrap wd-section"><div className="wd-section-heading"><p>YAŞAM ALANINIZA İLHAM</p><h2>KOLEKSİYONLARIMIZ</h2><p>Farklı tarzlar, doğal dokular ve size ait bir dünya.</p></div><div className="wd-collection-list">{collections.map(c => <Link className="wd-collection-row" href={`/koleksiyonlar/${c.slug}`} key={c.slug}><Photo src={c.image} alt={c.name}/><div><h3>{c.name}</h3><p>{c.description}</p></div><span className="wd-read-more">KOLEKSİYONU KEŞFET <span aria-hidden="true">&gt;</span></span></Link>)}</div></section>
    <section className="wd-contact-banner wd-factory-invite"><p>DOĞRUDAN ÜRETİCİNİZLE TANIŞIN</p><h2>Üretimi Yerinde Görün, Birlikte Tasarlayalım.</h2><p>Zenn Bedding olarak ürünlerimizi kendi üretim tesisimizde üretiyoruz. Ölçü, kumaş, renk ve tasarım seçeneklerini birlikte değerlendirerek ihtiyacınıza uygun çözümler oluşturuyoruz. Fabrikamızı ziyaret edin, ürünleri ve kumaşları yerinde inceleyin.</p><div className="actions"><Link href="/fabrikamiz" className="button">Fabrikamızı Ziyaret Edin</Link><a className="button outline" href={whatsappUrl("Merhaba, fabrikanızı ziyaret edip ürün ve kumaş seçeneklerini incelemek istiyorum.")}>WhatsApp’tan İletişime Geçin</a></div><FactoryGallery/></section>
    <References/><section className="wd-service-strip wrap"><div><span>◇</span><h3>Özenli tasarım</h3><p>Her detayda konfor</p></div><div><span>▱</span><h3>Zengin koleksiyon</h3><p>Yaşamınıza uygun seçenekler</p></div><div><span>✂</span><h3>Özel üretim</h3><p>Size özel ölçü ve kumaşlar</p></div><div><span>⌂</span><h3>Mağazamızı ziyaret edin</h3><Link href="/magazamiz">Esenyurt / İstanbul &gt;</Link></div></section>
  </>;
}
